version: '3.8'

services:

  laravel-vue-stocks:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel-vue-stocks
      DB_USERNAME: postgres
      DB_PASSWORD: password
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel-vue-stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

  webserver:
    image: nginx:latest
    depends_on:
      - laravel-vue-stocks
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
