services:

  laravel-vue-stocks:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel-vue-stocks
      DB_USERNAME: postgres
      DB_PASSWORD: password
    volumes:
      - .:/var/www/html
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    ports:
      - "8080:8080" # Reverb server
    networks:
      - laravel
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel-vue-stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  webserver:
    image: nginx:latest
    depends_on:
      - laravel-vue-stocks
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
  redisdata:
  storage_data:
  cache_data:
