<?php

return [
    'merv' => [
        'ALUA',
        'BYMA',
        'COME',
        'EDN',
        'GGAL',
        'METR',
        'PAMP',
        'YPFD'
    ],
    'spy' => [
        'AAPL',
        'ABEV',
        'ACHR',
        'AMD',
        'AMT',
        'AMZN',
        'ARKK', 
        'AVGO', 
        'AXP',
        'BABA', 
        'BAC',
        'BBAR',
        'BHP', 
        'BIDU', 
        'BIOX', 
        'BLK',
        'BMA',
        'BRFS', 
        'BRK.B',
        'BMY', 
        'CAR', 
        'CEPU',
        'CHPT',
        'COIN', 
        'COST',
        'CRESY',
        'DE',
        'DESP',
        'DIS', 
        'EA', 
        'EDN',
        'EEM', 
        'ERIC', 
        'ERJ', 
        'ETHA', 
        'EWZ',
        'F',
        'FSLR', 
        'FXI',
        'GGAL',
        'GLOB',
        'GME',
        'GOLD', 
        'GOOGL', 
        'GSAT', 
        'HD',
        'IBIT', 
        'INFY', 
        'INTC',
        'INTU',
        'IONQ',
        'IRS',
        'ITUB',
        'IWM',
        'JD', 
        'JNJ',
        'JPM',
        'KO', 
        'LAC',
        'LLY',
        'LMT',
        'LOMA',
        'LOW',
        'LUMN',
        'MA', 
        'MCD',
        'MDT',
        'MELI', 
        'META', 
        'MSFT', 
        'MSTR', 
        'MU', 
        'NIO',
        'NKE',
        'NVDA', 
        'NU',
        'PAM',
        'PBR',
        'PEP',
        'PFE',
        'PG', 
        'PLTR', 
        'PYPL', 
        'QBTS',
        'QQQ', 
        'QCOM', 
        'SATL', 
        'SBUX',
        'SE', 
        'SH',
        'SNAP',
        'SNOW',
        'SOLX',
        'SPXS',
        'SPY', 
        'SO',
        'SOXS',
        'SUPV',
        'TEO',
        'TGS',
        'TGT',
        'TSLA',
        'TSM',
        'UNH',
        'VALE', 
        'V', 
        'VEEV', 
        'VICI',
        'VIST',
        'VOO',
        'VZ', 
        'WBA', 
        'WFC', 
        'WM',
        'WMT', 
        'XLE',
        'XOM',
        'YPF',
    ],
    'criptoList' => [
        'cardano'              => 'ADA',
        'binancecoin'          => 'BNB',
        'biswap'               => 'BSW',
        'bitcoin'              => 'BTC',
        'pancakeswap-token'    => 'CAKE',
        'chiliz'               => 'CHZ',
        'crypto-com-chain'     => 'CRO',
        'polkadot'             => 'DOT',
        'ethereum'             => 'ETH',
        'fantom'               => 'FTM',
        'gala'                 => 'GALA',
        'internet-computer'    => 'ICP',
        'chainlink'            => 'LINK',
        'matic-network'        => 'MATIC',
        'near'                 => 'NEAR',
        'okb'                  => 'OKB',
        'pepe'                 => 'PEPE',
        'oasis-network'        => 'ROSE',
        'shiba-inu'            => 'SHIB',
        'solana'               => 'SOL',
        'sui'                  => 'SUI',
        'timber-token'         => 'TIMB',
        'the-open-network'     => 'TON',
        'tron'                 => 'TRX',
        'chia'                 => 'XCH',
        'monero'               => 'XMR',
        'ripple'               => 'XRP',
    ],
    'bonds' => [
        'BPOD7',
        'NDT25',
        'T17O5'
    ],
];
